(function() {var implementors = {};
implementors["objc_foundation"] = [{text:"impl&lt;T, O&gt; <a class=\"trait\" href=\"objc/message/trait.Message.html\" title=\"trait objc::message::Message\">Message</a> for <a class=\"struct\" href=\"objc_foundation/struct.NSArray.html\" title=\"struct objc_foundation::NSArray\">NSArray</a>&lt;T, O&gt;",synthetic:false,types:["objc_foundation::array::NSArray"]},{text:"impl&lt;T, O&gt; <a class=\"trait\" href=\"objc/message/trait.Message.html\" title=\"trait objc::message::Message\">Message</a> for <a class=\"struct\" href=\"objc_foundation/struct.NSMutableArray.html\" title=\"struct objc_foundation::NSMutableArray\">NSMutableArray</a>&lt;T, O&gt;",synthetic:false,types:["objc_foundation::array::NSMutableArray"]},{text:"impl <a class=\"trait\" href=\"objc/message/trait.Message.html\" title=\"trait objc::message::Message\">Message</a> for <a class=\"struct\" href=\"objc_foundation/struct.NSData.html\" title=\"struct objc_foundation::NSData\">NSData</a>",synthetic:false,types:["objc_foundation::data::NSData"]},{text:"impl <a class=\"trait\" href=\"objc/message/trait.Message.html\" title=\"trait objc::message::Message\">Message</a> for <a class=\"struct\" href=\"objc_foundation/struct.NSMutableData.html\" title=\"struct objc_foundation::NSMutableData\">NSMutableData</a>",synthetic:false,types:["objc_foundation::data::NSMutableData"]},{text:"impl&lt;K, V&gt; <a class=\"trait\" href=\"objc/message/trait.Message.html\" title=\"trait objc::message::Message\">Message</a> for <a class=\"struct\" href=\"objc_foundation/struct.NSDictionary.html\" title=\"struct objc_foundation::NSDictionary\">NSDictionary</a>&lt;K, V&gt;",synthetic:false,types:["objc_foundation::dictionary::NSDictionary"]},{text:"impl <a class=\"trait\" href=\"objc/message/trait.Message.html\" title=\"trait objc::message::Message\">Message</a> for <a class=\"struct\" href=\"objc_foundation/struct.NSObject.html\" title=\"struct objc_foundation::NSObject\">NSObject</a>",synthetic:false,types:["objc_foundation::object::NSObject"]},{text:"impl <a class=\"trait\" href=\"objc/message/trait.Message.html\" title=\"trait objc::message::Message\">Message</a> for <a class=\"struct\" href=\"objc_foundation/struct.NSString.html\" title=\"struct objc_foundation::NSString\">NSString</a>",synthetic:false,types:["objc_foundation::string::NSString"]},{text:"impl&lt;T&gt; <a class=\"trait\" href=\"objc/message/trait.Message.html\" title=\"trait objc::message::Message\">Message</a> for <a class=\"struct\" href=\"objc_foundation/struct.NSValue.html\" title=\"struct objc_foundation::NSValue\">NSValue</a>&lt;T&gt;",synthetic:false,types:["objc_foundation::value::NSValue"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
