(function() {var implementors = {};
implementors["objc_foundation"] = ["impl&lt;T, O&gt; <a class='trait' href='objc/message/trait.Message.html' title='objc::message::Message'>Message</a> for <a class='struct' href='objc_foundation/struct.NSArray.html' title='objc_foundation::NSArray'>NSArray</a>&lt;T, O&gt;","impl&lt;T, O&gt; <a class='trait' href='objc/message/trait.Message.html' title='objc::message::Message'>Message</a> for <a class='struct' href='objc_foundation/struct.NSMutableArray.html' title='objc_foundation::NSMutableArray'>NSMutableArray</a>&lt;T, O&gt;","impl <a class='trait' href='objc/message/trait.Message.html' title='objc::message::Message'>Message</a> for <a class='struct' href='objc_foundation/struct.NSData.html' title='objc_foundation::NSData'>NSData</a>","impl <a class='trait' href='objc/message/trait.Message.html' title='objc::message::Message'>Message</a> for <a class='struct' href='objc_foundation/struct.NSMutableData.html' title='objc_foundation::NSMutableData'>NSMutableData</a>","impl&lt;K, V&gt; <a class='trait' href='objc/message/trait.Message.html' title='objc::message::Message'>Message</a> for <a class='struct' href='objc_foundation/struct.NSDictionary.html' title='objc_foundation::NSDictionary'>NSDictionary</a>&lt;K, V&gt;","impl <a class='trait' href='objc/message/trait.Message.html' title='objc::message::Message'>Message</a> for <a class='struct' href='objc_foundation/struct.NSObject.html' title='objc_foundation::NSObject'>NSObject</a>","impl <a class='trait' href='objc/message/trait.Message.html' title='objc::message::Message'>Message</a> for <a class='struct' href='objc_foundation/struct.NSString.html' title='objc_foundation::NSString'>NSString</a>","impl&lt;T&gt; <a class='trait' href='objc/message/trait.Message.html' title='objc::message::Message'>Message</a> for <a class='struct' href='objc_foundation/struct.NSValue.html' title='objc_foundation::NSValue'>NSValue</a>&lt;T&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
