(function() {var implementors = {};
implementors["dispatch"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"enum\" href=\"dispatch/enum.QueueAttribute.html\" title=\"enum dispatch::QueueAttribute\">QueueAttribute</a>",synthetic:false,types:["dispatch::QueueAttribute"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"enum\" href=\"dispatch/enum.QueuePriority.html\" title=\"enum dispatch::QueuePriority\">QueuePriority</a>",synthetic:false,types:["dispatch::QueuePriority"]},];
implementors["objc"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"objc/runtime/struct.Sel.html\" title=\"struct objc::runtime::Sel\">Sel</a>",synthetic:false,types:["objc::runtime::Sel"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"objc/runtime/struct.Class.html\" title=\"struct objc::runtime::Class\">Class</a>",synthetic:false,types:["objc::runtime::Class"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"objc/runtime/struct.Protocol.html\" title=\"struct objc::runtime::Protocol\">Protocol</a>",synthetic:false,types:["objc::runtime::Protocol"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"objc/runtime/struct.Object.html\" title=\"struct objc::runtime::Object\">Object</a>",synthetic:false,types:["objc::runtime::Object"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"objc/struct.Encoding.html\" title=\"struct objc::Encoding\">Encoding</a>",synthetic:false,types:["objc::encode::Encoding"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"objc/struct.MessageError.html\" title=\"struct objc::MessageError\">MessageError</a>",synthetic:false,types:["objc::message::MessageError"]},];
implementors["objc_encode"] = [{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"enum\" href=\"objc_encode/enum.Encoding.html\" title=\"enum objc_encode::Encoding\">Encoding</a>&lt;'a&gt;",synthetic:false,types:["objc_encode::encoding::Encoding"]},];
implementors["objc_foundation"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"objc_foundation/struct.NSData.html\" title=\"struct objc_foundation::NSData\">NSData</a>",synthetic:false,types:["objc_foundation::data::NSData"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"objc_foundation/struct.NSMutableData.html\" title=\"struct objc_foundation::NSMutableData\">NSMutableData</a>",synthetic:false,types:["objc_foundation::data::NSMutableData"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"objc_foundation/struct.NSObject.html\" title=\"struct objc_foundation::NSObject\">NSObject</a>",synthetic:false,types:["objc_foundation::object::NSObject"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"objc_foundation/struct.NSString.html\" title=\"struct objc_foundation::NSString\">NSString</a>",synthetic:false,types:["objc_foundation::string::NSString"]},];
implementors["objc_id"] = [{text:"impl&lt;T, O&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"objc_id/struct.Id.html\" title=\"struct objc_id::Id\">Id</a>&lt;T, O&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a>,&nbsp;</span>",synthetic:false,types:["objc_id::id::Id"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
