(function() {var implementors = {};
implementors["objc_foundation"] = [{text:"impl&lt;T, O&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/index/trait.Index.html\" title=\"trait core::ops::index::Index\">Index</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.usize.html\">usize</a>&gt; for <a class=\"struct\" href=\"objc_foundation/struct.NSArray.html\" title=\"struct objc_foundation::NSArray\">NSArray</a>&lt;T, O&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: <a class=\"trait\" href=\"objc_foundation/trait.INSObject.html\" title=\"trait objc_foundation::INSObject\">INSObject</a>,<br>&nbsp;&nbsp;&nbsp;&nbsp;O: <a class=\"trait\" href=\"objc_id/id/trait.Ownership.html\" title=\"trait objc_id::id::Ownership\">Ownership</a>,&nbsp;</span>",synthetic:false,types:["objc_foundation::array::NSArray"]},{text:"impl&lt;T, O&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/index/trait.Index.html\" title=\"trait core::ops::index::Index\">Index</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.usize.html\">usize</a>&gt; for <a class=\"struct\" href=\"objc_foundation/struct.NSMutableArray.html\" title=\"struct objc_foundation::NSMutableArray\">NSMutableArray</a>&lt;T, O&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: <a class=\"trait\" href=\"objc_foundation/trait.INSObject.html\" title=\"trait objc_foundation::INSObject\">INSObject</a>,<br>&nbsp;&nbsp;&nbsp;&nbsp;O: <a class=\"trait\" href=\"objc_id/id/trait.Ownership.html\" title=\"trait objc_id::id::Ownership\">Ownership</a>,&nbsp;</span>",synthetic:false,types:["objc_foundation::array::NSMutableArray"]},{text:"impl&lt;'a, K, V&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/index/trait.Index.html\" title=\"trait core::ops::index::Index\">Index</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.reference.html\">&amp;'a </a>K&gt; for <a class=\"struct\" href=\"objc_foundation/struct.NSDictionary.html\" title=\"struct objc_foundation::NSDictionary\">NSDictionary</a>&lt;K, V&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;K: <a class=\"trait\" href=\"objc_foundation/trait.INSObject.html\" title=\"trait objc_foundation::INSObject\">INSObject</a>,<br>&nbsp;&nbsp;&nbsp;&nbsp;V: <a class=\"trait\" href=\"objc_foundation/trait.INSObject.html\" title=\"trait objc_foundation::INSObject\">INSObject</a>,&nbsp;</span>",synthetic:false,types:["objc_foundation::dictionary::NSDictionary"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
